# Generated by Django 5.0.2 on 2024-08-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='entries', to='earthling_api.tag'),
        ),
        migrations.DeleteModel(
            name='EntryTag',
        ),
    ]
